### ISSUE TITLE
project not working with zephyr 3.4

### ISSUE THREAD

**Issue by JakeMomo** [SoC-Arch-polito/ex23-pio-renode-uart#1]
When I try to create the example project using platorfmIO's UI, I get the error "Loading of Zephyr boilerplate.cmake directly is deprecated, please use\n 'find_package(Zephyr)". Maybe there is a way to tell platformIO to specifically use zephyr 2.7, which seems to work ?

**Comment by waltergallegog** [comment]
Hi @adoprix  thanks for the info provided. 
I have understood what is the issue.
Platformio has recently updated their support for zephyr and now officially support version 3.4.

By default with a new installation of platformio, it will download this version.

On my machine I still had the previously supported version (2.7).
The project sources (main.c, CMakeList.txt, prj.conf) work for zephyr version 2.7 and not for 3.4.

I will update the repo accordingly to support version 3.4. This should work in both Linux and Windows.

NOTE: I also tried setting the zephyr framework version to 2.7 in the .ini file, as we did yesterday in the lab, but it did not work. Even if the 2.7 version is downloaded and saved in the .pio folder, It then fails with error:
```
/home/walter/.platformio/penv/bin/python: can't open file '/home/walter/.platformio/packages/framework-zephyr@2.20701.220422/scripts/platformio/install-deps.py': [Errno 2] No such file or directory
```

Apparently in the version 3.4 of zephyr, a new `platformio/install-deps.py` file has been added. This file does not exists in the 2.7 version. For some reason PlatformIO is still searching for this file even if the version set is 2.7.
In any case, this is not a problem for us as we will just update the sources to support version 3.4

BR
Walter

**Comment by waltergallegog** [comment]
Update:
The reason the building fails when setting zephyr to version 2.7.1 is because the `platform` `ststm32` expects zephyr version 3.4:
https://github.com/platformio/platform-ststm32/releases

In version 17.0.0 of the platform, the zephyr version was updated.

To build the project using zephyr version 2.7.1 is enough to set the platform version to 16.1.0, the latest that supports the zephyr version 2.7.1:
```
[env]
platform = ststm32@~16.1.0
board = disco_f051r8
framework = zephyr
```

**Comment by JakeMomo** [comment]
Hello professor,

Thanks, the project now builds perfectly. However I still have the same 
error when trying to build a project for platformIO's UI :

```
"PIO Core Call Error: "Resolving disco_f051r8 dependencies...\nAlready 
up-to-date.\nUpdating metadata for the vscode
IDE...\n\n\nUserSideException: Processing disco_f051r8 (platform: 
ststm32; board: disco_f051r8; framework: 
zephyr)\n--------------------------------------------------------------------------------\nVerbose 
mode can be enabled via `-v, --verbose` option\nCONFIGURATION: 
https://docs.platformio.org/page/boards/ststm32/disco_f051r8.html\nPLATFORM: 
ST STM32 (17.0.0) > ST STM32F0DISCOVERY\nHARDWARE: STM32F051R8T6 48MHz, 
8KB RAM, 64KB Flash\nDEBUG: Current (stlink) On-board (stlink) External 
(blackmagic, cmsis-dap, jlink)\nPACKAGES: \n - framework-zephyr @ 
2.30400.230914 (3.4.0) \n - tool-cmake @ 3.21.3 \n - tool-dtc @ 1.4.7 \n 
- tool-gperf @ 3.0.4 \n - tool-ninja @ 1.7.1 \n - 
toolchain-gccarmnoneeabi @ 1.120301.0 (12.3.1)\nReading CMake 
configuration\n-- Application: 
/home/jacques/Documents/PlatformIO/Projects/test/zephyr\n-- CMake 
version: 3.21.3\n-- Found Python3: 
/home/jacques/.platformio/penv/.zephyr-3.4.0/bin/python3.10 (found 
suitable exact version \"3.10.12\") found components: Interpreter \n-- 
Cache files will be written to: /home/jacques/.cache/zephyr\n-- Zephyr 
version: 3.4.0 (/home/jacques/.platformio/packages/framework-zephyr), 
build: zephyr-v30400\n-- Board: stm32f0_disco\n-- Configuring 
incomplete, errors occurred!\n\nCMake Warning at 
/home/jacques/.platformio/packages/framework-zephyr/cmake/app/boilerplate.cmake:20 
(message):\n Loading of Zephyr boilerplate.cmake directly is deprecated, 
please use\n 'find_package(Zephyr)'\nCall Stack (most recent call 
first):\n CMakeLists.txt:2 (include)\n\n\nLoading Zephyr default modules 
(Zephyr base).\nCMake Error at 
/home/jacques/.platformio/packages/framework-zephyr/cmake/modules/configuration_files.cmake:76 
(message):\n No prj.conf file was found in the\n 
/home/jacques/Documents/PlatformIO/Projects/test/zephyr folder, please 
read\n the Zephyr documentation on application development.\nCall Stack 
(most recent call first):\n 
/home/jacques/.platformio/packages/framework-zephyr/cmake/modules/zephyr_default.cmake:115 
(include)\n 
/home/jacques/.platformio/packages/framework-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 
(include)\n 
/home/jacques/.platformio/packages/framework-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 
(include_boilerplate)\n 
/home/jacques/.platformio/packages/framework-zephyr/cmake/app/boilerplate.cmake:25 
(find_package)"
```
I added the entire error message so you have the fullpicture in case you 
need it. Tell me if you need me to open another github issue.

Best regards,

Jacques Morin

**Comment by waltergallegog** [comment]
Hi @adoprix 
Yes, please open a new issue.
In the new issue, please attach your project as  a compressed file.
From the error I see this:
```
No prj.conf file was found in the /home/jacques/Documents/PlatformIO/Projects/test/zephyr folder
```

**Comment by JakeMomo** [comment]
I'm sorry, I made a mistake in my previous mail : the error occurs when 
I try to create a new project.

I will open an issue.

Jacques Morin
